name: CI/CD for Express.js with PM2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: dev

    #  배포 디렉토리 준비
    - name: Prepare deployment directory
      run: |
        sudo mkdir -p /home/ubuntu/app
        sudo rm -rf /home/ubuntu/app/*
        sudo cp -r . /home/ubuntu/app

    # .env 파일 생성
    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/app/.env
        sudo chmod 600 /home/ubuntu/app/.env

    # Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 종속성 설치
    - name: Install dependencies
      run: |
        cd /home/ubuntu/app
        sudo npm install

    # PM2로 서버 재시작
    - name: Restart Server
      run: |
        cd /home/ubuntu/app
        sudo pm2 stop express-app || true
        sudo pm2 start app.js --name express-app
        sudo pm2 save
